language: node_js
node_js:
 — 12
branches:
 only:
 — master
notifications:
  email: akapoor3@ucmerced.com
cache:
  npm: false
before_script:
 - npm i -g npm@6.14.8
 — npm install -g ionic
 — npm ci
script:
 — ionic build --prod -- --base-href ./
deploy:
 provider: pages
 skip_cleanup: true
 cleanup: true
 github-token: $GITHUB_TOKEN
 keep_history: true
 on:
   branch: master
 local_dir: www
 repo: Apro123/SusMap
 target_branch: gh-pages
 project_name: Sustainability Map
 name: Armaan Kapoor
 email: akapoor3@ucmerced.edu
