branches:
 only:
 - master
 - /v\d+\.\d+[a-z]/
notifications:
  email: akapoor3@ucmerced.edu
jobs:
  include:
  - os: linux
    dist: xenial
    language: node_js
    node_js:
      - 12
    env: TRGT=browser
cache:
  npm: false
before_script:
 - npm i -g npm@7.7.6
 — npm install -g @ionic/cli@6.14.1 cordova@10.0.0
 — npm ci
script:
 — ./buildproj.sh
#before_deploy:
#  # Set up git user name and tag this commit
#  - git config --local user.name "Apro123"
#  - git config --local user.email "akapoor3@ucmerced.edu"
#  - git tag $PROJ_VERSION
#  - git commit -m "added tag"
#  - git push origin master && git push origin master --tags
deploy:
 - provider: releases
   tag_name: $PROJ_VERSION
   name: $PROJ_NAME
   body: "SusMap"
   skip_cleanup: true
   api_key: $GITHUB_TOKEN
   overwrite: true
   file: $PROJ_ZIP
   on:
     tags: true
     repo: Apro123/SusMap
     branch: master
