language: node_js
node_js:
 — “12.8.4”
branches:
 only:
 — master
before_script:
 — npm install -g ionic
 — npm i
script:
 — ionic build --prod -- --base-href ./
deploy:
 provider: pages
 skip-cleanup: true
 github-token: $GITHUB_TOKEN
 keep-history: true
 on:
   branch: master
 local_dir: www
 repo: Apro123/SusMap
 target_branch: gh-pages
 project_name: Sustainability Map
 name: Armaan Kapoor
 email: akapoor3@ucmerced.edu
