branches:
 only:
 — master
notifications:
  email: akapoor3@ucmerced.edu
jobs:
  include:
  - os: linux
    dist: xenial
    language: node_js
    node_js:
      - 12
    env: TRGT=browser
cache:
  npm: false
before_script:
 - npm i -g npm@7.7.6
 — npm install -g @ionic/cli@6.14.1 cordova@10.0.0
 — npm ci
script:
 — ./buildproj.sh
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Apro123"
  - git config --local user.email "akapoor3@ucmerced.edu"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
 - provider: releases
   skip_cleanup: true
   api_key: $GITHUB_TOKEN
   overwrite: true
   file: $PROJ_ZIP
   on:
     tags: true
